In [82]:
import pandas as pd
dataset = pd.read_csv('WELFake_Dataset.csv')

In [83]:
dataset.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [84]:
dataset.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [85]:
dataset.shape

(72134, 4)

In [86]:
dataset = dataset.dropna()

In [87]:
dataset.shape

(71537, 4)

In [88]:
X = dataset.drop('label', axis=1)
y = dataset['label']

In [89]:
X.shape

(71537, 3)

In [53]:
y = y.iloc[:10000]

In [90]:
y.shape

(71537,)

In [91]:
y

0        1
2        1
3        0
4        1
5        1
        ..
72129    0
72130    1
72131    0
72132    0
72133    1
Name: label, Length: 71537, dtype: int64

In [92]:
X.head()

,Unnamed: 0,title,text
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ..."
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will..."
5,5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...

In [93]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM, Dense

In [94]:
# Vocabulary size
voc_size = 5000

### One-Hot Encoding

In [95]:
messages = X.copy()

In [96]:
messages.head()

,Unnamed: 0,title,text
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ..."
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will..."
5,5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...

In [32]:
messages = messages.iloc[:10000, :]

In [97]:
messages.shape

(71537, 3)

In [98]:
# messages.reset_index(inplace=True)

In [99]:
import nltk
import re
from nltk.corpus import stopwords

In [100]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Adarsh
[nltk_data]     Kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [101]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for title in messages['title']:
    # re.sub -> (substitute) all the special characters with space
    review = re.sub('[^a-zA-Z]', ' ', title)
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [102]:
corpus[:5]

['law enforc high alert follow threat cop white blacklivesmatt fyf terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti bid',
 'satan russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group']

In [103]:
onehot_repr = [one_hot(words, voc_size) for words in corpus]

In [104]:
onehot_repr

[[2317, 2443, 450, 1630, 268, 769, 4410, 4950, 1003, 2960, 985, 449],
 [2741,
  2116,
  2601,
  2734,
  1248,
  564,
  1183,
  3733,
  331,
  1975,
  4633,
  4383,
  2011,
  449],
 [768, 987, 2464, 2126, 2511, 2576, 2238, 4700, 2635, 1058, 3353, 3899],
 [2444, 1709, 1306, 3093, 3890, 2048, 1103, 3812, 356, 790, 3217],
 [4622, 2238, 2878, 3898, 1019, 1361, 2399, 919, 2878],
 [57, 4759, 4685, 2749, 4838, 1783, 3005, 3998, 3982, 2945, 2053],
 [1890, 2063, 3622, 2029, 1709, 4632, 2576, 3519, 2071, 449],
 [1983,
  2087,
  4833,
  403,
  1530,
  2064,
  1959,
  4747,
  3049,
  1983,
  1501,
  4244,
  4058,
  694,
  449],
 [4876, 3009, 3748, 4113, 753, 445, 1164, 3009],
 [4119, 2946, 2730, 4815, 3187, 1596, 4525, 4708],
 [2412, 3608, 3781, 1738, 4659, 3584, 4998, 956, 4998, 3662],
 [1437, 1039, 2029, 4404, 2709, 377, 1209, 2670, 2919],
 [2629, 999, 3213, 1039, 3704, 577, 2797, 2834, 4733, 4369, 832],
 [254, 1380, 689, 3927, 3516, 2733, 1541, 4918, 822, 40],
 [4710, 2869, 964, 3354, 1694, 1890, 2524],
 [63, 2532, 1642, 3012, 1530, 1466, 3556, 1079, 2035],
 [4818, 2745, 1466, 4651, 3917, 2846, 3300, 4806],
 [4341,
  2747,
  2729,
  138,
  4051,
  2788,
  1944,
  2029,
  2665,
  3704,
  1205,
  4769,
  2660,
  2941],
 [1848, 1908, 1248, 2834, 3897, 1919, 2412, 4582, 4223],
 [694, 4821, 4281, 74, 2799],
 [2396, 4733, 4369, 2085, 779, 4818],
 [145, 2197, 216, 2341, 717, 2029, 3897, 2645, 2753, 449],
 [1918, 3184, 2396, 2834, 3950, 3112, 3644, 957, 565, 709],
 [4979, 2029, 932, 665, 3636, 1382, 4863, 2174, 727, 3644, 449],
 [1753, 3272, 3430, 1738, 955, 1574, 1175, 4564, 2566],
 [4745, 4761, 1152, 2458, 3488, 3014, 2062, 762, 2048, 2670, 4622],
 [2303, 4633, 1756, 2237, 382, 4965, 4159],
 [2946, 1335, 4821, 4633, 273, 783, 2837, 567, 691, 2048, 2670, 4622],
 [3543, 2255, 2426],
 [2939, 2511, 4829, 2799, 2340, 4622, 502, 1818],
 [4516, 1114, 832, 1101, 553, 457, 4768, 3997, 2048, 2670, 4622],
 [235, 1904, 366, 3594, 75, 3904, 1453, 164, 1028, 3456, 3921, 3218],
 [4071, 1885, 2236, 3662, 565, 3598, 498],
 [4818, 748, 3242, 2029, 2122, 2462, 1798, 4383, 4777, 2068, 47],
 [2834, 3868, 2570, 2029, 4479, 3445, 1845],
 [3636, 2477, 591, 1705, 2601, 3205, 449],
 [3448, 773, 272, 4043, 782, 4629, 4681, 1368, 4492, 3060],
 [127, 1124, 3380, 2048, 2670, 4622, 1967, 449],
 [3302, 2703, 770, 4011, 2029, 2319, 449],
 [1079, 1979, 1947, 725, 4011, 2029, 3562],
 [4787, 1709, 1350, 778, 2443, 2187, 4664, 1664, 1205, 2048, 2670, 4622],
 [1642,
  2116,
  3780,
  2802,
  1894,
  4574,
  519,
  808,
  741,
  2133,
  3056,
  2396,
  3897,
  2447,
  2396],
 [2029, 1248, 3608, 4680, 2514, 518, 1869, 1798, 1284, 3038],
 [2652, 1380, 1633, 317, 73, 2117, 3714, 691, 1501, 426],
 [984, 2011, 374, 2048, 2670, 4622],
 [3505, 1890, 846, 4209, 3283, 3200, 1814, 2356],
 [4622, 4897, 2488, 3495],
 [2706, 3007, 2265, 1709, 2048, 2670, 1760, 2048, 2670, 4622],
 [3049, 2081, 2594],
 [2674, 3669, 2734, 1323, 1718, 3593, 4043, 1686, 1458],
 [4588, 4916, 1383, 677, 1349, 2282, 2048, 2670, 4622],
 [4818, 1810, 1816, 663, 1498, 2331, 2749],
 [2029, 4058, 4108, 1082, 3622, 3927, 3377, 2712, 3324, 593],
 [2118, 2882, 3238, 2570, 4707, 4207, 2029, 530, 179, 1986, 1458],
 [1597, 2281, 3178, 4249, 741, 696, 1579, 517],
 [3367, 445, 529, 2981, 1383, 2025, 4140, 4209, 3161],
 [4695, 4749, 4637, 1284, 1765, 2198, 2044, 2048, 376],
 [1646, 1867, 3709, 75, 2706, 2029, 1944, 40],
 [4818, 1890, 2849, 4144, 2980, 1105, 3584],
 [681, 2515, 3644, 2029, 4119, 806, 3003, 1519, 2396],
 [2068, 4629, 422, 2947, 1539, 3630, 3375, 1944, 518, 2947, 1539],
 [3925, 4699, 9, 649, 4119, 3806, 2104, 4896, 3851, 4520, 2374],
 [1234, 3572, 73, 1405, 1143, 4638, 2396, 4950, 1890, 3899],
 [3205, 1145, 2289, 395, 356, 1461, 2712],
 [4119, 1117, 2029, 3530, 691, 1501, 1098, 1716, 3492, 3170, 331],
 [2029, 292, 4679, 182, 1466, 4679, 3283, 4184],
 [1122, 1457, 4208],
 [3298, 2071, 862, 663, 4108, 403],
 [2396,
  4749,
  1836,
  4486,
  268,
  1466,
  449,
  2026,
  9,
  1855,
  4721,
  3508,
  688,
  2396,
  2047],
 [4011, 2029, 547, 4326, 3463, 4979, 3127, 2048, 2670, 4622],
 [2488, 2640, 756, 873, 233, 3297, 2882],
 [4011, 2029, 2466, 4788, 4632, 1979],
 [4269, 4548, 2029, 616, 4466, 273, 1407, 2476],
 [4680, 1161, 1860, 4089, 2471, 3940],
 [3324, 2524, 2701, 103, 1664, 1819, 1223, 4080],
 [3048, 1709, 342, 339, 1696, 2085, 3806, 4555, 694],
 [4950, 1890, 4019, 4990, 2946, 3612, 574, 4144],
 [1080, 1766, 4279, 4677, 4358, 1560],
 [3036, 1142, 156, 4956, 2417, 2029, 772],
 [4144, 3744, 3056, 841, 1006, 3376],
 [3811, 4047, 3927, 4196, 1525, 4622, 4632, 220, 2341],
 [3847, 2153, 790, 4933, 1524, 4644, 1594, 3093, 2048, 2670, 4622],
 [1101, 2116, 2213, 2048, 1322, 1035, 2447, 1035],
 [4818, 4448, 1959, 3644, 1011, 2187],
 [3275, 1642, 1905, 1744, 4890, 4821, 1310, 1705, 626, 1035],
 [2116, 577, 2029, 1709, 434, 652, 1321, 3286],
 [1767,
  2834,
  4278,
  4048,
  2532,
  2133,
  3157,
  1820,
  2423,
  4144,
  2834,
  3704,
  4697,
  3571,
  1890,
  1664,
  2488],
 [1623, 2029, 702, 4996, 1291, 4818, 4633],
 [1050, 327, 3038, 1117, 3878, 1642, 4918, 3584, 4184, 2356],
 [1383, 1505, 1079, 2118, 2625, 2048, 2670, 4622],
 [2029, 3523, 3681, 403, 2938, 4745, 4777, 1798, 1284],
 [1069, 1346, 71, 1696, 1899, 2213, 4587, 2317, 3456, 4896, 3888, 2311, 449],
 [4378,
  2198,
  202,
  267,
  3036,
  3595,
  4695,
  1765,
  1030,
  3328,
  1547,
  919,
  2029,
  449],
 [2029, 3380, 73, 1075, 1035, 3233, 2938, 1028],
 [4533, 273, 2794, 3430, 4888, 2706, 2781],
 [2515, 1864, 4652, 2674, 1173, 3811, 3218, 2740],
 [2214, 4707, 1944, 741, 336, 1501, 1714, 1241],
 [1899,
  2261,
  508,
  3299,
  1767,
  4454,
  1213,
  4410,
  919,
  2780,
  2116,
  304,
  3898,
  1122,
  1679,
  249,
  1676,
  4550],
 [3179, 3998, 3191, 66, 600, 2029, 331, 4298, 4080, 2477],
 [395, 702, 1987, 4396, 4721, 769, 2048, 2670, 4622],
 [4378,
  4264,
  199,
  2396,
  1497,
  2001,
  4147,
  470,
  1083,
  4893,
  2396,
  133,
  2200,
  2590,
  3799,
  449],
 [2629,
  1908,
  4996,
  4225,
  2976,
  2477,
  3616,
  1441,
  2781,
  1965,
  1101,
  3036,
  2802],
 [356, 985, 3437, 694],
 [2331, 4197, 1189, 2391, 1944, 999],
 [1351, 4199, 3888, 2448, 600, 2029, 769, 2412, 3934],
 [3448, 4630, 2257, 779, 3560, 470, 4622, 1091, 7],
 [919, 4329, 2116, 687, 4788, 2029, 2204, 2179, 3662, 4479, 2339, 3765],
 [519, 1171, 164, 4135, 3078, 3849, 3353, 4290, 2669, 1117, 881, 1288],
 [1079, 1851, 4123, 355, 4821, 2026, 939, 3322, 4707, 4672, 4488, 2396],
 [780, 1455, 4923, 800, 2251, 1147, 931, 449],
 [2236, 2477, 912, 4830, 3857, 741, 1293, 4140, 2048, 2670, 4622],
 [4147, 4024, 1097, 4045, 3170, 4622],
 [3811, 3179, 3014, 1855, 2339, 3013, 2779],
 [3448, 353, 1079, 1965, 4435, 2297, 3888, 1079, 1965, 4435, 2998, 2249],
 [3880,
  3049,
  242,
  3781,
  3000,
  457,
  3530,
  2511,
  928,
  4480,
  3880,
  3049,
  1303,
  82],
 [4712, 1959, 1407, 409, 3049, 3975, 2029],
 [2630, 3505, 1859, 4950, 3253, 4437, 2117, 9, 3994, 449],
 [2048, 2670, 805, 773, 832, 4633, 1057, 3940],
 [2400, 3013, 1524, 3878, 2400, 2485, 168, 2048, 2670, 4622],
 [2029, 2019, 687, 3150, 550],
 [2396, 2002, 133, 727, 547],
 [2939, 2511, 244, 2085, 4108, 3120, 4089],
 [3112, 273, 1836, 2029, 2546, 1478, 2198, 4494, 40],
 [4011,
  2029,
  3283,
  4773,
  1959,
  3878,
  4310,
  3283,
  61,
  2712,
  3120,
  4622,
  3834,
  2048,
  2670,
  4622],
 [4602, 2029, 1035, 1438, 1296, 3402, 3367, 1798, 1284],
 [3899, 4633, 2340, 4089, 2396, 1164, 449],
 [1105, 2417, 449, 2029, 480, 3636, 1760, 3470, 1979, 4156, 4293],
 [3310, 1738, 4028, 2610, 4089, 1340, 4168],
 [4466, 1426, 2724, 4092, 1545, 2694, 2486, 3012, 3858, 1677, 1106, 1865],
 [3797, 4295, 2787, 2014],
 [4312, 3731, 4454, 2783, 4199, 2204, 2597, 4384, 1596, 1634, 1030],
 [804, 4626, 2198, 220, 1075, 4708, 1323, 3253, 1110, 1137, 40],
 [1983, 1207, 2458, 2328, 4089, 1011, 1596, 4787, 2317],
 [1642, 2588, 2328, 1908, 3630, 2116, 4890, 2313, 4598, 4698, 2825],
 [3639, 1959, 2026, 9, 4959, 3013, 4633, 2511, 4402, 3013, 2313],
 [1271, 1039, 4549, 979, 329, 254, 395, 942],
 [4324, 2834, 3109, 3376],
 [1762, 2317, 852, 676, 3205, 1469, 2448, 3940, 3594, 449],
 [2629, 2961, 220, 1765, 1039, 1944, 2116, 3703, 465, 1461, 1794],
 [4712, 3067, 3014, 1030, 3221, 889, 2048, 2670, 4622],
 [2961, 1765, 770, 2247, 2396, 2834, 332, 3897, 46, 434],
 [2433, 2412, 2117, 405, 254, 4369, 1011, 2281, 1919],
 [1055, 2834, 3853, 1738, 2552, 3940, 2055, 2048, 2670, 4622],
 [1079, 769, 2029, 1398, 3404, 404],
 [2118, 1574, 218, 2433, 2137, 498, 3790, 3487, 3450, 2674],
 [3155, 2938, 1944, 2029, 1836, 2048, 2670, 4622],
 [2834, 916, 2029, 4479, 1788, 4405],
 [3800,
  3205,
  3296,
  2981,
  3161,
  1384,
  845,
  82,
  510,
  2968,
  717,
  2645,
  3367,
  2475,
  2879,
  366,
  3594,
  913],
 [3608,
  3931,
  2340,
  1798,
  498,
  3820,
  1785,
  4818,
  3595,
  4818,
  1338,
  2048,
  2670,
  4622],
 [3937, 2029, 3984, 1555, 3367, 2945, 3623, 2048, 577, 567, 4144, 40],
 [666, 2116, 4297, 1376, 1832, 1390, 2261, 3745, 3361],
 [1008, 2048, 3548, 1530, 2701, 1080, 2358],
 [928, 4761, 4104, 4640, 4774, 912, 2257],
 [510,
  3312,
  3691,
  1248,
  2116,
  4787,
  676,
  1427,
  1627,
  3049,
  1368,
  1474,
  2879,
  3078,
  4249,
  2303,
  2002],
 [2116, 2935, 4119, 769, 912, 4745, 4761, 2396, 3165],
 [1788, 4707, 3309, 403, 2780, 1199, 4549, 40],
 [257, 567, 3960, 4016, 3243, 3353, 741, 2048, 2670, 4622],
 [2515, 1864, 4652, 3811, 1794],
 [4602, 2029, 1035, 4367, 1858, 4680, 2876, 779],
 [2029, 2557, 2534, 1908, 2341],
 [332, 1828, 999, 3178, 4011, 2029, 4399, 4672, 434],
 [3046,
  4979,
  3127,
  4011,
  2029,
  3017,
  4633,
  1332,
  2396,
  2834,
  2048,
  2670,
  4622],
 [3988, 2029, 1248, 4341, 4341, 3977, 4383, 4777, 3372, 1466, 3100],
 [1340, 3744, 3788, 4264, 2047, 3508, 403, 3014, 2725, 2029, 1596, 449],
 [3104, 4361, 403, 1940, 2214, 1716],
 [2029, 2721, 741, 474, 434, 2961, 220, 2044],
 [358,
  717,
  2745,
  4777,
  1848,
  1603,
  982,
  1476,
  2163,
  626,
  4341,
  805,
  4818,
  123],
 [3988, 4310, 1248, 4608, 1030, 3878, 2087, 1340],
 [4812, 2832, 2029, 881, 4548, 1205, 2048, 2670, 4622],
 [4296, 1959, 1891, 2304, 1642, 1939, 2246, 2001, 4369, 449],
 [12, 969, 2256, 1006, 309, 2783, 2814, 258, 2048, 2670, 4622],
 [4707, 1982, 790, 54, 2029, 1039, 2702, 3423],
 [2029, 4818, 4704, 2605, 1248, 2255, 4950, 1890],
 [2629,
  2514,
  273,
  310,
  4548,
  3570,
  3798,
  398,
  4879,
  1727,
  3229,
  2532,
  2331,
  1030,
  1890,
  968,
  2621],
 [1321, 3064, 2172, 1940, 2449, 2200, 2799, 2529, 2048, 2071],
 [4378,
  2747,
  3775,
  2863,
  770,
  4127,
  1691,
  1352,
  3014,
  3863,
  3179,
  3940,
  4084,
  2251,
  1340,
  663,
  3014,
  3863,
  449],
 [4011, 2029, 221, 2560, 587, 4486, 939, 3322],
 [2789, 3879, 1110, 2476, 934, 2085],
 [4197, 1323, 702, 552, 694, 2340, 2022],
 [2396, 2834, 4745, 4761, 4518, 4089, 3562, 3036],
 [4165, 2412, 3982, 769, 1267, 1832, 1482, 985, 741, 2803, 1501, 40],
 [3356, 4588, 843, 4295, 4722, 2029, 3014, 3049, 597],
 [2029, 2257, 3127, 845, 1039, 1951, 4188],
 [2029, 2180, 3157, 489, 3055, 1184, 1699, 786, 3977, 2048, 2670, 4622],
 [4033, 4440, 4637, 4868, 1986],
 [3950, 3074, 1101, 2240, 2730, 3643, 3376, 4198],
 [4846, 199, 4672, 1109, 2048, 2670, 4622],
 [1507, 2236, 3458, 696, 2048, 2833, 2955, 4885, 4581, 271],
 [3140, 3450, 4457, 1217, 380, 4286, 2375, 3508, 2048, 2670, 4622],
 [4977, 20, 2757, 2396, 3062, 3180, 3179, 2878, 1855, 3535],
 [4345, 3258, 547, 2876, 912, 914, 3060, 3205, 2048, 2670, 4622],
 [1035, 4548, 2029, 3748, 2391, 4629, 2242, 2396, 3897],
 [1709, 1884, 707, 321, 2048, 4818, 3547, 4144, 247],
 [2747, 1979, 3609, 469, 4749, 1232, 1248, 84, 1709, 2582, 3426, 449],
 [3179, 999, 434, 2616, 3003, 4494, 3811, 1498],
 [403, 3298, 3656, 1161, 2709],
 [4761, 4996, 1492, 4564, 3508, 1461, 4016],
 [484, 2515, 2836, 4672, 2024, 3782, 2048, 2670, 4622],
 [785, 1677, 2961, 2898, 781, 4818, 4777, 1191, 2129],
 [1079, 694, 2495, 356, 1461],
 [4369, 1376, 4067, 4578, 766, 4127, 3520, 2020, 3191, 912, 2180],
 [600, 2029, 2882, 99, 2029, 3644, 1794, 4993, 3157, 1775, 449],
 [2174, 1819, 295, 4833, 403, 4410, 1855, 2598, 404, 470, 449],
 [1932, 1944, 2466, 4339, 470, 3078, 1818, 2833, 2048, 2670, 4622],
 [3448, 4445, 766, 3448, 528, 4950, 3415, 3445, 227, 3669, 1205, 3312],
 [449, 2396, 2834, 933, 2849, 1644, 805, 3367, 2475],
 [1642,
  375,
  1340,
  2020,
  466,
  4632,
  2118,
  4204,
  4386,
  103,
  3014,
  3863,
  2845,
  2590],
 [4710, 4011, 2029, 3731, 2447, 2122, 2604],
 [2029, 1248, 3853, 3056, 1253, 4818],
 [2341, 3253, 2781, 2048, 2670, 1688, 4384, 4818, 40],
 [2116, 235, 3470, 4949, 4209, 57, 4759, 4685, 591, 688, 327, 3878, 2269, 449],
 [2601, 2734, 3402, 3074, 1196, 1709, 770],
 [784, 1461, 2341, 1405, 4313, 1855, 3296, 646, 1642, 4326, 3525],
 [2834, 3934, 539, 3038, 449],
 [375, 3787, 2938, 2281, 4135, 2029, 9, 1349, 2883, 40],
 [4818, 3078, 2156, 2939, 1028, 4724, 2259, 1908, 4089],
 [2029, 976, 1879, 4996, 4761, 3014, 3059, 623],
 [4574, 1248, 2029, 1202, 1801, 2568, 4282],
 [2029, 1477, 4086, 4081, 1563, 2048, 3361],
 [3286,
  4921,
  2981,
  2745,
  939,
  2755,
  1957,
  3627,
  987,
  84,
  850,
  2048,
  2670,
  4622],
 [4987, 1892, 3056, 210, 968, 4776],
 [3310, 3172, 470, 2167, 4144, 756, 4989],
 [1642, 220, 2834, 1137, 3730, 4996, 2396, 1078, 3934],
 [2029, 554, 166, 618, 2116, 2555, 2553, 3253],
 [1709, 717, 2412, 912, 1794, 327, 465, 4598],
 [2200, 1287, 3446, 1420, 1326, 4454, 2048, 2670, 4622],
 [1944, 2029, 4576, 1884, 1731, 4191, 2946, 481, 1836],
 [2458, 4761, 1908, 1205, 4011, 2029, 702, 4996, 4062, 40],
 [2029, 3180, 1962, 3518, 1738, 1962, 4967, 2523, 3622],
 [2740, 1542, 4189, 4680, 220, 1323, 4486, 395, 776, 4632, 220, 449],
 [4339, 2311, 234, 2228, 1717, 2002, 1932, 1400, 4077, 1248],
 [1890, 790, 3169, 4391, 2116, 1694, 2964, 2237, 3211, 985, 2781, 4950, 1890],
 [2405, 4717, 390, 4830, 2763, 4876, 856, 3354, 2048, 2670, 4622],
 [999,
  2629,
  4025,
  3951,
  4410,
  687,
  4062,
  75,
  2029,
  3951,
  4282,
  2029,
  2895,
  449],
 [2629, 4748, 4385, 2029, 3180, 1836, 449],
 [1642, 220, 2029, 4962, 1705, 103, 3283, 4184, 2327, 103, 3283, 2945, 449],
 [4103, 1501, 2198, 820, 1614, 1820, 2539, 2289, 3036, 434],
 [1519,
  2340,
  3748,
  510,
  1629,
  4466,
  105,
  1699,
  1498,
  1243,
  3685,
  3639,
  4396,
  2927,
  573,
  2289,
  530,
  2748],
 [4011, 2029, 3165, 1944, 2119, 3562],
 [4383, 2011, 2396, 3644, 2395, 4630, 3013, 4090, 4622],
 [356, 1461, 1967],
 [4574, 3595, 2116, 3812, 1979, 3559, 3530, 498, 4297, 1959, 467, 1238],
 [2629, 4897, 2200, 999, 499, 2029, 4499, 772, 4296, 1959],
 [4785, 1949, 537, 2781, 4913, 769],
 [449, 1959, 3801, 1532, 2412, 254, 1493, 668, 3349, 4043, 3490, 449],
 [4818, 3853, 3598, 1248, 2303, 4633, 2187, 1928, 1458, 2712],
 [4159, 3013, 403, 3049, 3897, 2029, 702, 4996, 40],
 [3488, 1209, 2061, 2864, 779, 1124, 289, 1199, 1243, 3557, 449],
 [2396, 4486, 133, 727, 547, 449],
 [3448, 553, 974, 2553, 470, 248, 48, 272, 974, 1979, 577],
 [510, 4879, 1727, 1340, 1944, 1208, 873, 2048, 2670, 4622],
 [4303, 593, 2029, 2911, 1851, 1520, 4784],
 [2747, 3285, 4269],
 [2566, 4606, 1323],
 [1971, 3809, 499, 3487, 687, 1816, 1079, 2281],
 [2116, 702, 2356, 1145, 7, 4745, 4761, 2048, 2670, 4622],
 [2008, 3587, 4892, 518, 694, 4163, 2238, 4950, 40],
 [2629, 2029, 2189, 2651, 510, 1705, 2712, 3940, 1738, 1783, 576, 4778],
 [4818, 4745, 4761, 3377, 4341, 762, 2116, 702, 2356],
 [2629, 4749, 1232, 2433, 2523, 3622, 2029, 3283, 2466, 3062, 449],
 [4926, 2798, 2767, 976, 3332, 4818, 1966, 2638],
 [4329, 539, 2198, 4140, 2048, 4850, 889],
 [610, 4717],
 [662, 1039, 2869, 3487, 769, 3982, 2545],
 [310, 2801, 1884, 3982, 790, 3487, 2800],
 [4818, 2946, 2938, 1296, 3402, 3734, 2017, 2601, 2734],
 [3508, 688, 3285, 1332, 4622, 4549, 3049, 520, 2518],
 [510, 4818, 2601, 4634, 2063, 2776, 1533, 2029, 449],
 [1350, 1248, 1911, 1445, 2305, 4818, 762, 1932, 3503],
 [1642, 2834, 3342, 4048, 2317, 2610, 2834, 4633, 2340, 539, 14, 3793, 3486],
 [4819, 1324, 1039, 528, 1340, 3598, 1030, 530, 580, 3321],
 [2240, 1867, 367, 4399, 4383, 2011, 3172, 4454],
 [2156, 3854, 2116, 4319, 770, 1145],
 [2780, 2834, 2878, 2213, 676, 3112, 1461, 3213, 2029],
 [3950, 1860, 1248, 3001, 9, 2068, 2487, 957],
 [2029, 790, 4679, 3283, 3322, 3878, 1842, 409, 1501, 2116, 2048, 2670, 4622],
 [4182, 3802, 4913, 497, 2105, 2629, 2502, 1240],
 [1350, 4687, 4579, 2835, 1011, 638, 489, 19],
 [92, 1944, 2947, 4818, 774, 1893, 2733, 3623, 2713],
 [2462, 1039, 606, 3391, 3692, 4161, 235, 4576, 2960],
 [2396,
  1128,
  2200,
  3013,
  851,
  3669,
  4632,
  2941,
  2256,
  1545,
  4872,
  4008,
  4144,
  449],
 [4196,
  4942,
  1979,
  537,
  1783,
  3321,
  3639,
  851,
  1979,
  342,
  4787,
  2396,
  2882,
  2019],
 [255,
  1211,
  547,
  4479,
  2118,
  3330,
  2300,
  1334,
  4189,
  1039,
  1035,
  2511,
  4582,
  1137,
  4788,
  2029,
  3283,
  4144],
 [877, 3330, 896, 4552, 2712, 3940, 2048, 2670, 4622],
 [1831, 3165, 2340, 4178, 3321, 1340, 1101, 1906],
 [694, 1340, 342, 3623, 2984, 2153],
 [3310, 3172, 470, 1573, 4223, 2715, 3993, 2048, 2670, 4622],
 [2447, 1944, 2029, 1477, 3653, 2447, 2417, 2048, 2670, 4622],
 [841, 2757, 4326, 4989, 1466, 2251, 4800, 2235, 741],
 [790, 449, 1949, 3296, 1783, 4411],
 [4282, 2895, 1890, 3013, 4092, 2029, 2895, 210, 3013],
 [264, 3592, 2354, 3165, 762, 4697, 1942, 821, 2048, 2670, 4622],
 [3075, 4307, 3899, 4684, 2029, 3012, 403],
 [331, 2749, 2029, 4282, 103, 3300, 2417],
 [2029, 879, 1962, 2340, 2044, 1248, 734, 4144, 1711, 74, 2396, 449],
 [1995, 2834, 1501, 3423, 3237, 4331, 3808, 375, 1328],
 [4540, 225, 2029, 4696, 3014, 3796, 1011, 1340],
 [],
 [4950, 1890, 1248, 4555, 4276, 614, 3208, 1340, 790, 3681],
 [4818, 2745, 3574, 4207, 2545, 2095, 2947, 4913, 2011],
 [2029, 1330, 2339, 3622, 2095, 2678, 3523],
 [2116, 4196, 3756, 1562, 2545, 1199, 4959, 1541],
 [2624, 2863, 4676, 3375, 191, 2327, 1855, 437, 4518, 449],
 [2029, 4698, 4996, 1946, 3783, 403, 2610, 4698, 3630, 2020],
 [2545, 1423],
 [310, 4207, 2029, 1959, 4990, 4885, 4517, 1946, 4758],
 [1869, 3563, 4768, 373, 2412, 4979, 1260],
 [2799, 2493, 3734, 3665, 985, 3179, 4476, 593, 3502, 2662],
 [4633, 2340, 2740, 3897, 4773, 1418],
 [3488, 2214, 75, 766, 4585, 4361, 4993, 4217, 2938, 3878, 4597, 75],
 [1124, 2246, 846, 3616, 2116, 124, 1199],
 [2671, 4622, 1644, 805, 2740],
 [1908, 3902, 1724, 2396, 3897, 3878, 3897, 2488, 3312, 1234, 3691, 449],
 [4871, 1445, 4586, 3239, 1928, 878, 643, 3625, 1495, 1303, 4159],
 [851, 2152, 2834, 3109, 3897, 1028, 665, 4144],
 [375, 152, 2514, 1967, 27, 798],
 [2629, 2029, 465, 3179, 932, 1944, 2662, 2119, 2199, 2849, 3322],
 [4602, 3899, 2672, 1652, 2702, 2029, 3375, 3822, 806],
 [1507, 4633, 2594, 4733],
 [3775, 4633, 843, 75, 1248, 985, 741, 3255, 3879, 1303, 449],
 [3367, 936, 4140, 4097, 4871, 4821, 3508, 3367, 3013, 1596],
 [4933, 4787, 3049, 4372, 3430, 2950],
 [870, 2029, 778, 4723, 3155, 4576, 2879, 1398, 3404, 3781],
 [2629, 2703, 1205, 4119, 753, 1988, 3800, 2662],
 [2029, 2180, 2317, 2935, 4297, 4369, 3074, 2029, 600, 4447, 434],
 [2119, 4622, 3814, 4909],
 [694, 790, 3487, 1139, 790, 3487, 4846, 4196],
 [3593, 327, 1124, 1015, 1718, 3662, 3013, 1627, 22, 3172, 3593, 1979],
 [3389, 105, 2940, 331, 1762, 4848, 690, 3700, 4097, 40],
 [2029, 2749, 702, 4818, 167, 3616, 1842, 4074],
 [2787, 2511, 2118, 3156, 684, 1458, 1377],
 [484, 597, 828, 1292, 1340, 892, 668, 1257, 4457, 449],
 [246, 3543, 746, 3217, 2517, 2340, 4089, 356],
 [3811, 333, 4286, 1248, 2034, 4581, 1574, 136, 1248, 3461, 3177, 3218],
 [1979, 3038, 4985, 1376, 2246, 1281, 342, 4739, 3133, 4725, 3273],
 [1753, 1908, 1704, 1435, 2048, 2787, 3046, 1260, 2116, 449],
 [2236, 1855, 985, 3424, 1974, 1898, 4934, 32],
 [4848, 1574, 61, 1303, 2532, 1811, 2200, 1959, 4140, 3426, 741, 4743, 2305],
 [3049, 979, 912, 4135, 437, 4509, 382, 498, 979, 1398, 3404],
 [3456, 1762, 3, 2715, 53, 4129, 196, 2863],
 [748, 985, 2048, 4116, 4011, 2029, 92, 1039, 2048, 2670, 4622],
 [2174,
  3714,
  1914,
  3983,
  805,
  2095,
  2105,
  2342,
  2503,
  4622,
  1398,
  2238,
  1379,
  2095,
  1458,
  466,
  449,

In [105]:
corpus[1]

'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video'

In [106]:
onehot_repr[1]

[2741,
 2116,
 2601,
 2734,
 1248,
 564,
 1183,
 3733,
 331,
 1975,
 4633,
 4383,
 2011,
 449]

### Embedding Representation

In [107]:
sent_length = 20
embedding_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [108]:
embedding_docs

array([[   0,    0,    0, ..., 2960,  985,  449],
       [   0,    0,    0, ..., 4383, 2011,  449],
       [   0,    0,    0, ..., 1058, 3353, 3899],
       ...,
       [   0,    0,    0, ..., 3487, 4579, 3678],
       [   0,    0,    0, ..., 2117, 3191, 1376],
       [   0,    0,    0, ..., 2396, 2834, 1944]],
      shape=(71537, 20), dtype=int32)

In [109]:
# Creating model
embedding_vector_features = 40 # features representation
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length=sent_length))
model.build(input_shape=(None, sent_length)) 
model.add(LSTM(100)) # LSTM layer with 100 neurons
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

d:\coding\github\NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [110]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 100)            │        56,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           101 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 256,501 (1001.96 KB)

 Trainable params: 256,501 (1001.96 KB)

 Non-trainable params: 0 (0.00 B)

In [111]:
len(embedding_docs), y.shape

(71537, (71537,))

In [112]:
import numpy as np
X_final = np.array(embedding_docs)
y_final = np.array(y)

In [113]:
X_final.shape, y_final.shape

((71537, 20), (71537,))

In [114]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

In [115]:
# Model Training
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 24s 23ms/step - accuracy: 0.8627 - loss: 0.3106 - val_accuracy: 0.8974 - val_loss: 0.2414
Epoch 2/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 21s 23ms/step - accuracy: 0.9108 - loss: 0.2192 - val_accuracy: 0.9008 - val_loss: 0.2355
Epoch 3/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 20s 23ms/step - accuracy: 0.9247 - loss: 0.1873 - val_accuracy: 0.9008 - val_loss: 0.2413
Epoch 4/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 21s 23ms/step - accuracy: 0.9341 - loss: 0.1639 - val_accuracy: 0.8989 - val_loss: 0.2693
Epoch 5/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 21s 23ms/step - accuracy: 0.9431 - loss: 0.1422 - val_accuracy: 0.8972 - val_loss: 0.2778
Epoch 6/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 20s 23ms/step - accuracy: 0.9511 - loss: 0.1222 - val_accuracy: 0.8976 - val_loss: 0.3015
Epoch 7/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 20s 23ms/step - accuracy: 0.9595 - loss: 0.1027 - val_accuracy: 0.9004 - val_loss: 0.3271
Epoch 8/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 20s 23ms/step - accuracy: 0.9669 - loss: 0.0846 - val_accuracy: 0.8982 - val_loss: 0.3704
Epoch 9/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 21s 23ms/step - accuracy: 0.9726 - loss: 0.0699 - val_accuracy: 0.8979 - val_loss: 0.3997
Epoch 10/10
895/895 ━━━━━━━━━━━━━━━━━━━━ 21s 23ms/step - accuracy: 0.9770 - loss: 0.0567 - val_accuracy: 0.8987 - val_loss: 0.4912

### Performance Metrics and Accuracy

In [117]:
y_pred = model.predict(X_test)

448/448 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step

In [118]:
y_pred = np.where(y_pred > 0.5, 1, 0) # AUC ROC Curve

In [119]:
from sklearn.metrics import confusion_matrix

In [120]:
confusion_matrix(y_test, y_pred)

array([[6299,  782],
       [ 667, 6560]])

In [121]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8987279843444227

In [122]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.89      0.90      7081
           1       0.89      0.91      0.90      7227

    accuracy                           0.90     14308
   macro avg       0.90      0.90      0.90     14308
weighted avg       0.90      0.90      0.90     14308